# Generated by Django 4.2 on 2023-05-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(help_text='razão social da empresa contratada', max_length=200, verbose_name='Razão Social')),
                ('address', models.CharField(help_text='endereço da empresa contratada', max_length=200, verbose_name='Endereço')),
                ('phone_fax', models.CharField(help_text='telefone para contato', max_length=50, verbose_name='Telefone/Fax')),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ', max_length=50, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, help_text='endereço e-Mail', max_length=254, null=True, verbose_name='endereço e-Mail')),
                ('responsible_contact', models.CharField(help_text='Nome do Responsável Técnico', max_length=80, verbose_name='nome do responsável técnico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='número de inscrição', max_length=50, verbose_name='número de inscrição')),
                ('description', models.CharField(help_text='nome da autarquia', max_length=200, verbose_name='nome da autarquia')),
            ],
        ),
        migrations.CreateModel(
            name='ContractedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(help_text='razão social da empresa contratada', max_length=200, verbose_name='Razão Social')),
                ('address', models.CharField(help_text='endereço da empresa contratada', max_length=200, verbose_name='Endereço')),
                ('phone_fax', models.CharField(help_text='telefone para contato', max_length=50, verbose_name='Telefone/Fax')),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ', max_length=50, verbose_name='CNPJ')),
                ('other_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.otherdocuments', verbose_name='Outros Documentos (licenças, registros e afins')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='other_documents',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.otherdocuments', verbose_name='Outros documentos'),
            preserve_default=False,
        ),
    ]
