# Generated by Django 4.2 on 2023-07-26 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contractingcompany_otherdocuments_contractedcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(help_text='razão social da empresa contratada', max_length=200, verbose_name='Razão Social')),
                ('address', models.CharField(help_text='endereço da empresa contratada', max_length=200, verbose_name='Endereço')),
                ('phone_fax', models.CharField(help_text='telefone para contato', max_length=50, verbose_name='Telefone/Fax')),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ', max_length=50, verbose_name='CNPJ')),
                ('other_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.otherdocuments', verbose_name='Outros Documentos (licenças, registros e afins)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='ContractingCompany',
            new_name='Client',
        ),
        migrations.DeleteModel(
            name='ContractedCompany',
        ),
    ]
