# Generated by Django 4.2 on 2023-10-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_environmentalconsultancy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='nome da matriz', max_length=200, verbose_name='matriz')),
            ],
        ),
    ]
