# Generated by Django 4.2 on 2024-08-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descrição de Amostra', max_length=80, verbose_name='descricao de amostra')),
                ('evalueted_local_sector', models.CharField(help_text='Setor Avaliado', max_length=80, verbose_name='setor avaliado')),
                ('collection_time', models.CharField(help_text='Hora da Coleta', max_length=80, verbose_name='hora da coleta')),
                ('collection_date', models.CharField(help_text='Data da Coleta', max_length=80, verbose_name='data da coleta')),
            ],
        ),
    ]
