# Generated by Django 4.2 on 2024-11-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_parameter_rename_otherdocuments_documents_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.RenameField(
            model_name='environmentalconsultancy',
            old_name='documents',
            new_name='document',
        ),
    ]
