# Generated by Django 4.2 on 2024-11-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_documents_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='nome do produto', max_length=200, verbose_name='produto')),
                ('code', models.CharField(help_text='código', max_length=50, verbose_name='código')),
                ('amount', models.CharField(help_text='quantidade', max_length=50, verbose_name='quantidade')),
                ('price', models.DecimalField(decimal_places=2, help_text='valor do produto', max_digits=10, verbose_name='preço')),
            ],
        ),
    ]
