# Generated by Django 4.2 on 2024-11-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(help_text='Objetivo da Proposta', max_length=300, verbose_name='objetivo')),
                ('collection_date', models.DateField(help_text='data de coleta')),
                ('legal_basis', models.CharField(help_text='Objetivo da Proposta', max_length=300, verbose_name='objetivo')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='nickname',
            field=models.CharField(default='nickname', help_text='apelido ou abreviação', max_length=200, verbose_name='empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environmentalconsultancy',
            name='nickname',
            field=models.CharField(default='nickname', help_text='apelido ou abreviação', max_length=200, verbose_name='empresa'),
            preserve_default=False,
        ),
    ]
