# Generated by Django 4.2 on 2024-11-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_proposal_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='services',
            field=models.ManyToManyField(help_text='Lista de Serviços', related_name='proposals', to='web.service', verbose_name='serviços'),
        ),
    ]
